(() => {
'use strict';
const R=window.RAM=window.RAM||{};
R.repo='https://github.com/JTech-CO/RAM';
R.commit='a2c3cbd63b7058c0853e7197e22d660017d0087c';
R.profiles={
 SRAM:{num:'01',name:'Static RAM',subtitle:'되먹임으로 기억하는 회로.',short:'래치 · 6T',unit:'6T / BIT',badge:'VOLATILE',color:'#b0d8ff',file:'01-sram.md',concept:'논리 전압의 안정 상태',intro:'두 인버터가 서로를 구동하며 Q와 Q̅을 반대 상태로 유지합니다. 6개 트랜지스터 중 4개는 기억을, 2개는 접근을 담당합니다.',facts:[['저장 매체','교차 결합 인버터'],['저장 단위','1 bit / 6 transistors'],['읽기 특성','비파괴적 · 차동 센싱'],['상태 유지','전원 필요 · 리프레시 없음']],formula:'Q̅ = NOT Q',formulaNote:'인버터의 입력과 출력을 교차 연결한 두 안정 상태. 6T는 대표 셀이며 모든 SRAM 구현이 6T인 것은 아닙니다.',data:'캐시라인·명령·레지스터 파일의 데이터도 결국 0/1의 논리 상태로 저장됩니다. 셀은 데이터가 숫자인지 문자열인지 알지 못합니다.',caveat:'대표적인 평면 MOS 단면과 6T 연결을 보여줍니다. 실제 FinFET·GAA SRAM의 파운드리 레이아웃, 소자 크기, 잡음 마진 및 동적 전력은 재현하지 않습니다.',sourceIds:['repo','sram']},
 DRAM:{num:'02',name:'Dynamic RAM',subtitle:'저장된 전하가 데이터가 되는 순간.',short:'커패시터 · 1T1C',unit:'1T1C / BIT',badge:'VOLATILE',color:'#9be6cd',file:'02-dram.md',concept:'커패시터의 저장 전압',intro:'트랜지스터가 문을 열면 커패시터의 전하가 비트라인과 나뉩니다. 작은 차이를 증폭하고 원래 전압으로 복원하는 과정이 읽기입니다.',facts:[['저장 매체','커패시터 + 접근 MOS'],['저장 단위','1 bit / 1T1C'],['읽기 특성','전하 공유 · 감지 · 복원'],['상태 유지','주기적인 리프레시 필요']],formula:'ΔVBL = Cc / (Cc + Cb) × (Vcell − VDD/2)',formulaNote:'이 실험은 VDD=1 V, Cc:Cb=1:10을 가정합니다. 실제 제품값이 아니라 전하 보존을 보여주기 위한 예시이며, 접속된 플레이트는 VDD/2로 유지됩니다.',data:'메인 메모리는 CPU가 사용하는 프로그램 코드와 작업 데이터를 보관합니다. 주소를 행과 열로 나누어 행을 연 뒤, 센스 앰프의 행 버퍼에서 필요한 부분을 꺼냅니다.',caveat:'그림의 커패시터 크기와 주변 셀 간격은 비례하지 않습니다. 감지와 복원은 실제로 겹쳐 일어나지만 단계별 학습을 위해 분리했습니다. 누설 모델은 실측 분포가 아닌 예시입니다.',sourceIds:['repo','dram','dramResearch']},
 HBM:{num:'03',name:'High Bandwidth Memory',subtitle:'더 빠른 셀보다, 더 넓은 데이터 길.',short:'DRAM 적층 · TSV',unit:'STACKED DRAM',badge:'VOLATILE',color:'#a8cfff',file:'03-hbm.md',concept:'DRAM 저장 + 병렬 인터페이스',intro:'동일한 1T1C 저장 원리를 쓰는 DRAM 다이를 수직으로 쌓습니다. TSV와 인터포저가 많은 데이터 경로를 가속기 가까이 연결합니다.',facts:[['저장 매체','DRAM의 1T1C 셀'],['배열 구조','여러 다이 · 여러 뱅크'],['주요 이점','넓은 병렬 전송 경로'],['상태 유지','DRAM처럼 복원·리프레시']],formula:'Bandwidth = bus width × transfer rate ÷ 8',formulaNote:'예시: 1,024 bit × 6.4 Gbit/s/pin ÷ 8 = 819.2 GB/s. 산술 예제이며 현재 화면의 8개 대표 경로나 특정 제품의 실효 성능을 뜻하지 않습니다.',data:'가속기 연산에 필요한 텐서·활성값·KV 캐시 등도 비트 배열입니다. 높은 병렬 대역폭은 많은 데이터를 연속 공급하는 데 유리하지만, 한 셀의 접근 지연이 그 비율만큼 줄어드는 것은 아닙니다.',caveat:'8단 스택과 8개 경로는 구조 설명용입니다. 채널은 다이와 1:1 대응하지 않으며, 이 화면의 뱅크·레이어 선택은 서로 다른 탐색 축입니다. 열·전력·JEDEC 명령 타이밍은 계산하지 않습니다.',sourceIds:['repo','hbm']},
 HBF:{num:'04',name:'High Bandwidth Flash',subtitle:'플래시의 용량을, 병렬 경로로.',short:'NAND 기반 · 병렬 I/O',unit:'NAND-BASED',badge:'NON-VOLATILE',color:'#cab6ed',file:'04-hbf.md',concept:'NAND 저장 + 높은 병렬성',intro:'셀에서는 NAND처럼 전하를 가두고 문턱 전압으로 읽습니다. 독립적인 배열 접근과 가속기 인접 데이터 경로가 대역폭을 확대합니다.',facts:[['저장 매체','NAND의 전하 저장층'],['데이터 특성','비휘발성 · 읽기 중심'],['쓰기를 바꾸는 제약','프로그램 / 블록 소거'],['구현 범위','공개 구조 기반 개념 모델']],formula:'Parallel throughput ≠ single-access latency',formulaNote:'서브어레이의 동시 접근과 인터페이스 폭은 대역폭을 높이지만, 개별 NAND 센싱의 지연을 없애지 않습니다. 이 앱은 HBF의 제품별 지연·내구성 값을 추정하지 않습니다.',data:'대규모 추론의 모델 가중치처럼 용량과 읽기 대역폭을 함께 요구하는 데이터가 대표적인 활용 대상으로 제시됩니다. 실제 요청 입도·큐·매핑·보존 관리 정책은 구현 및 사양에 의존합니다.',caveat:'2026-09-10 확인한 공개 자료를 토대로 한 개념 시각화입니다. 모든 HBF가 SSD처럼 장기간 무관리 보존을 보장하는 것은 아닙니다. 본 화면의 물리 페이지·블록 실험을 호스트 API와 동일시하지 마세요.',sourceIds:['repo','hbf2026','hbf','nand']},
 NAND:{num:'05',name:'3D NAND Flash',subtitle:'전하를 가두고, 문턱을 읽다.',short:'전하 트랩 · 3D 스트링',unit:'CHARGE TRAP',badge:'NON-VOLATILE',color:'#d8bb8d',file:'05-nand.md',concept:'저장 전하가 바꾸는 문턱 전압',intro:'절연층 안에 포획된 전하가 트랜지스터의 문턱 전압을 바꿉니다. 수직으로 연결한 셀 스트링에서 선택한 셀의 도통 여부를 읽습니다.',facts:[['저장 매체','전하 트랩층 · CTF 예시'],['셀당 정보량','SLC 1 / MLC 2 / TLC 3 / QLC 4 bit'],['읽기·쓰기','페이지 단위의 센싱·프로그램'],['소거 단위','여러 페이지를 포함한 블록']],formula:'N states = 2^(bits per cell)',formulaNote:'TLC는 8개 상태로 3비트를 표현합니다. 앱의 Gray 코드 매핑과 정규화 Vt 분포는 예시입니다. 실제 업체의 매핑, 분포 폭, 읽기 순서는 다를 수 있습니다.',data:'소프트웨어는 파일이나 논리 블록을 보지만, NAND 셀은 문턱 상태만 보관합니다. 일반 SSD의 컨트롤러는 논리 주소를 물리 페이지에 매핑하며 ECC·마모 분산·가비지 컬렉션을 관리합니다.',caveat:'CTF 기반 3D NAND의 대표 구조입니다. 모든 NAND가 CTF는 아니며, 그림의 8개 WL과 8개 셀 표본은 실제 층수나 페이지 크기가 아닙니다. MLC 이상에서 한 WL의 셀 상태는 여러 논리 페이지에 걸친 정보를 표현하며, 이 앱은 이를 한 번에 프로그램하는 추상 모델입니다. 이 앱은 FTL·실제 ECC·ISPP 전압 파형을 에뮬레이션하지 않습니다.',sourceIds:['repo','nand','mlc','trap']}
};
R.sources=[
 {id:'repo',label:'JTech-CO / RAM · 참고 저장소',org:'Reference repository',url:'https://github.com/JTech-CO/RAM/tree/a2c3cbd63b7058c0853e7197e22d660017d0087c',note:'01–05장: 셀 구조, 데이터 접근 원리, 계층 구분. 특정 제품 수치와 공정 설명은 앱의 계산 모델에 사용하지 않았습니다.'},
 {id:'sram',label:'6T SRAM Cell',org:'TU Wien · Robert Entner doctoral thesis',url:'https://www.iue.tuwien.ac.at/phd/entner/node34.html',note:'교차 결합 인버터, 액세스 트랜지스터, 보존·읽기·쓰기 원리.'},
 {id:'dram',label:'DRAM: array, core and periphery',org:'Applied Materials',url:'https://www.appliedmaterials.com/us/en/semiconductor/markets-and-inflections/memory/dram.html',note:'셀 배열, 센스 앰프·워드라인 디코더, 외부 I/O의 구분.'},
 {id:'dramResearch',label:'Shifting in-DRAM',org:'Research paper · arXiv:2602.24269v1',url:'https://arxiv.org/html/2602.24269v1',note:'ACTIVATE, charge sharing, sense amplification, restore, READ/WRITE, PRECHARGE.'},
 {id:'hbm',label:'HBM · 1T1C / TSV / base die / interposer',org:'RAM chapter 03 · pinned revision',url:'https://github.com/JTech-CO/RAM/blob/a2c3cbd63b7058c0853e7197e22d660017d0087c/03-hbm.md',note:'HBM을 새로운 저장 셀이 아니라 DRAM 기반의 적층·인터페이스 구조로 구분.'},
 {id:'hbf2026',label:'First HBF standard specifications at FMS 2026',org:'SK hynix · 2026-08-04',url:'https://news.skhynix.com/en/hbf-at-fms-2026/',note:'Sandisk와의 HBF 공개 사양 발표 및 NAND 기반 고대역폭 메모리 구상. 발표 수치를 동작 보증값으로 재사용하지 않았습니다.'},
 {id:'hbf',label:'Inside High Bandwidth Flash for AI',org:'Sandisk · 2025',url:'https://www.sandisk.com/company/newsroom/blogs/2025/scaling-beyond-the-wall-inside-sandisks-high-bandwidth-flash-for-ai',note:'NAND 기반 HBF와 AI 추론 활용 방향. 미공개 장치 내부 구현은 개념 모델로 한정.'},
 {id:'nand',label:'What is NAND Flash Memory?',org:'KIOXIA · Research & Development',url:'https://www.kioxia.com/en-jp/rd/technology/nand-flash.html',note:'절연층으로 둘러싸인 전하 저장층과 비휘발성 저장의 기본 원리.'},
 {id:'mlc',label:'Multi-level Cell Technology',org:'KIOXIA · Research & Development',url:'https://www.kioxia.com/en-jp/rd/technology/multi-level-cell.html',note:'저장 전하·문턱 전압, 셀당 비트 수와 구분 가능한 상태 수.'},
 {id:'trap',label:'Hole-Trapping in SiN Films',org:'KIOXIA · 2023-07-12',url:'https://www.kioxia.com/en-jp/rd/technology/topics/topics-47.html',note:'트랩 전하가 Vth에 영향을 미치는 CTF 저장 원리. 리텐션을 무한대로 취급하지 않음.'}
];
const shared={
 substrate:['실리콘 기판','Silicon substrate','접근 트랜지스터와 주변회로를 지지하는 반도체 영역입니다. 색상은 물질 구분용이며 실제 현미경 색상이 아닙니다.'],
 wl:['워드라인','Word line / gate control','행을 선택하는 제어선입니다. WL을 통해 데이터 자체가 저장되는 것이 아니라, 게이트 전압이 셀의 접근을 제어합니다.'],
 bl:['비트라인','Bit line / data path','선택 셀의 전기적 상태를 센싱 회로로 전달하고, 쓰기 구동을 셀에 전달하는 경로입니다.'],
 sense:['센스 앰프','Sense amplifier','미세한 전압차 또는 전류 차를 증폭해 디지털 논리로 판정하는 주변회로입니다. SRAM·DRAM·NAND에서 입력 물리량과 동작 방식이 다릅니다.'],
 buffer:['데이터 버퍼','Row / page buffer','센싱 결과를 잠시 유지하고 데이터 인터페이스와 연결하는 회로입니다. DRAM 행 버퍼와 NAND 페이지 버퍼는 같은 소자는 아닙니다.'],
};
R.parts={
 SRAM:{...shared,latch:['교차 결합 인버터','Cross-coupled inverters','두 CMOS 인버터의 출력이 상대편 입력으로 되돌아갑니다. 하나의 출력이 높으면 다른 출력은 낮아지는 양의 되먹임 구조입니다.'],q:['저장 노드 Q','Storage node','사용자가 읽는 0 또는 1에 대응하는 논리 전압입니다. 반대편 Q̅과 항상 상보 상태를 이루는 정상 동작을 모델링합니다.'],qb:['상보 저장 노드 Q̅','Complementary storage node','Q가 1일 때 Q̅은 0입니다. 6T SRAM의 두 노드는 2비트가 아니라 한 비트의 상보 표현입니다.'],access:['액세스 트랜지스터 2개','Access / pass-gate NMOS','같은 WL에 제어되는 두 NMOS가 Q–BL, Q̅–BL̅ 경로를 동시에 연결합니다. 나머지 4개 트랜지스터는 래치입니다.'],blb:['상보 비트라인 BL̅','Complementary bit line','BL과 한 쌍으로 사용됩니다. 읽기는 작은 차이를 판정하고, 쓰기는 두 선을 서로 반대 전압으로 강하게 구동합니다.']},
 DRAM:{...shared,plate:['공통 플레이트','Common capacitor plate','커패시터의 반대쪽 전극입니다. 이 예시에서는 VDD/2에 고정합니다. 저장 전하의 부호와 양은 저장 노드와 플레이트 사이 전압차에 따라 달라집니다.'],dielectric:['고유전율 절연막','Capacitor dielectric','두 전극이 직접 도통하지 않도록 분리하면서 전기장을 형성합니다. 얇고 높은 커패시턴스를 얻는 구조를 보여주지만 치수·재료 조성은 제품 모델이 아닙니다.'],storage:['저장 전극 / 저장 노드','Storage electrode / node','접근 MOS와 연결된 커패시터 전극입니다. 읽기 중 비트라인과 전하를 공유한 뒤 센스 앰프로 원래 전압을 복원합니다.'],access:['접근 트랜지스터','Access MOSFET','게이트가 WL에 연결되어 있습니다. 켜지면 저장 노드와 BL을 연결하고, 꺼지면 전하를 가두지만 완전한 무누설 스위치는 아닙니다.'],capacitor:['주변 1T1C 셀','Neighboring cells','한 비트씩 저장하는 주변 셀의 축약 구조입니다. 선택 셀은 절연막과 전극을 보기 위해 더 크게 표현했습니다.'],contact:['저장 노드 컨택','Storage-node contact','접근 트랜지스터의 확산 영역과 저장 커패시터 전극을 전기적으로 연결합니다.']},
 HBM:{...shared,processor:['가속기','Processor / accelerator','메모리 데이터를 받아 연산하는 별도 로직 다이입니다. 본 시각화에서 HBM 다이 자체가 텐서 연산을 수행하는 것으로 표현하지 않았습니다.'],die:['적층 DRAM 다이','Stacked DRAM dies','각 다이에 뱅크와 1T1C 셀 배열이 있습니다. 다이 수와 채널 수는 동일한 개념이 아니며 서로 1:1로 연결되지 않습니다.'],bank:['뱅크와 배열','Banks / memory arrays','행을 여는 단위와 병렬 접근 자원을 제공합니다. 화면의 타일은 구조를 설명하는 대표 블록이며 실제 주소 비트 배치가 아닙니다.'],tsv:['실리콘 관통 전극','Through-silicon via','다이를 관통하는 전기 연결입니다. 신호·전원·접지용 TSV가 존재하며, 모든 TSV가 독립 데이터 핀인 것은 아닙니다.'],base:['베이스 다이','Base die / I/O logic','상부 메모리 다이와 외부 인터페이스 사이의 데이터 경로를 연결합니다. 로직 기능과 컨트롤러 분담은 세대 및 제품에 따라 달라집니다.'],interposer:['인터포저','Interposer / package wiring','가속기와 스택 사이의 많은 연결을 짧은 거리로 배치합니다. 넓은 데이터 경로는 대역폭을 높이지만 셀의 리프레시 필요성은 그대로입니다.']},
 HBF:{...shared,processor:['가속기','Processor / accelerator','NAND 기반 대용량 데이터 계층을 활용하는 호스트입니다. 호스트의 실제 요청 형식과 캐싱 정책은 이 모델의 단순화된 데이터 경로와 다를 수 있습니다.'],die:['적층 NAND 다이','NAND die stack','다이 내부의 수직 NAND WL 적층과 여러 다이의 패키지 적층은 서로 다른 두 층위입니다. 이 장면은 패키지 적층을 보여줍니다.'],bank:['병렬 서브어레이','Parallel subarrays','여러 NAND 센싱 작업을 겹쳐 수행하는 대표 구조입니다. 각 개별 읽기의 지연이 짧아진 것과 동시 처리량이 커진 것을 구분해야 합니다.'],tsv:['수직 연결','Vertical electrical connections','적층 다이의 데이터 경로를 제어 로직으로 연결하는 개념 표현입니다. 정확한 내부 토폴로지나 핀 배치를 재현하지 않습니다.'],base:['버퍼와 제어 로직','Page buffers / controller path','센싱 결과를 모으고 오류 정정 및 데이터 이동을 조율하는 경로입니다. 페이지·블록 단위 제약이 호스트에 노출되는 방식은 구현에 따라 달라집니다.'],interposer:['근접 데이터 연결','Near-accelerator interconnect','용량이 큰 NAND 계층을 가속기 가까이 배치해 데이터 공급을 개선하는 개념입니다. HBM과 동일 소켓에 그대로 꽂는 호환성을 뜻하지 않습니다.'],cba:['배열과 CMOS 로직','Array / CMOS separation','NAND 배열과 주변 CMOS 로직을 결합하는 구조적 구분을 표시합니다. CBA 본딩 자체가 모든 병렬화 알고리즘을 자동으로 제공하는 것은 아닙니다.']},
 NAND:{...shared,wordline:['선택 워드라인','Selected word line','같은 WL의 여러 스트링 셀을 함께 제어합니다. 선택 WL에는 읽기 기준, 비선택 WL에는 충분한 통과 바이어스를 걸어 선택 셀의 도통 여부를 구분합니다.'],trap:['전하 트랩층','Charge-trapping dielectric','절연막 속의 트랩에 전하를 포획합니다. 트랩 전하가 주변 채널의 문턱 전압을 바꾸며, 이 차이를 디지털 상태로 해석합니다.'],channel:['수직 채널','Vertical semiconductor channel','여러 셀이 공유하는 직렬 전류 경로입니다. 모든 비선택 셀이 통과 상태여도 선택 셀이 꺼져 있으면 전체 스트링 전류가 제한됩니다.'],tunnel:['터널 절연막','Tunnel dielectric','채널과 저장층 사이의 절연막입니다. 프로그램 때의 전하 이동과 보존 때의 격리를 구분해야 합니다. 광점은 개별 전자의 실제 궤적이 아닙니다.'],blocking:['블로킹 절연막','Blocking dielectric','저장층과 제어 게이트 사이를 분리합니다. 다양한 유전체 스택을 대표 층으로 단순화했습니다.'],select:['스트링 선택 게이트','Drain / source select gates','스트링의 양 끝 연결을 선택합니다. 데이터 저장 WL과 달리 스트링 전체의 전류 경로를 제어합니다.'],source:['공통 소스라인','Common source line','여러 NAND 스트링이 공유하는 소스 측 연결입니다. 실제 바이어스와 소거 방식은 셀 구조에 따라 다릅니다.']}
};
})();
